name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.9
