name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  core:
    path: ../core

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
